### ISSUE TITLE
Soporte para el tag de condiciones

### ISSUE THREAD

**Issue by frcepeda** [omegaup/libkarel#1]
Cuál sería la mejor manera para exponer tags de este estilo?

https://github.com/ComiteMexicanoDeInformatica/OMI-2016/blob/master/Karel/La%20muerte%20de%20Karel/cases/1sub.1.in#L2

**Comment by lhchavez** [comment]
~puedes leer el `.in` original abriendo el archivo mágico `data.in`. eso te es suficiente?~

algo así como `KarelInput.limites.avanza == 2`? pero de cualquier manera si te pasas del límite, karel.js interrumpe la ejecución.

**Comment by frcepeda** [comment]
Ah, sí, pero es para poder correr los tests de los casos de prueba

Onda checar que "sólo puedes avanzar N veces donde N es el alto del mundo"

**Comment by lhchavez** [comment]
Arreglado en 1c740041d33677aaa69cac7fbd5d48266e408c04.
